name: silencia
description: "Silencia - Application de messagerie sécurisée avec chiffrement de bout en bout."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: 1.4.0
  shared_preferences: ^2.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3
  go_router: ^13.2.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  file_selector: ^1.0.3
  file_picker: ^8.0.0+1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.0.4
  video_player: ^2.8.1
  convert: ^3.1.1
  pointycastle: ^3.9.1
  basic_utils: ^5.7.0
  bip39: ^1.0.6
  cryptography: ^2.7.0
  path: ^1.9.0
  share_plus: ^7.2.2
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Firebase dependencies for push notifications
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.4.0

  # Nouvelles dépendances pour améliorer le fonctionnement
  # Monitoring et logs
  logger: ^2.0.2+1
  # sentry_flutter: ^7.18.0  # Temporairement désactivé
  firebase_crashlytics: ^3.4.8

  # Performance et cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UX/UI améliorée
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.2

  # Sécurité renforcée
  local_auth: ^2.1.8
  device_info_plus: ^10.1.0
  package_info_plus: ^9.0.0

  # Fonctionnalités avancées
  url_launcher: ^6.2.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1

  # Audio packages pour messages vocaux
  just_audio: ^0.10.4
  record: ^6.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

  # Test dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets pour Silencia
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Configuration des icônes Silencia
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/silencia_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/silencia_icon.png"
    background_color: "#f5f5f5"
    theme_color: "#2c5f5f"
  windows:
    generate: true
    image_path: "assets/icons/silencia_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
