// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHewRjH34GC2g4D4nh7Tcuf_0_odbCWjg',
    appId: '1:495262766796:web:your-web-app-id',
    messagingSenderId: '495262766796',
    projectId: 'app-5642b',
    authDomain: 'app-5642b.firebaseapp.com',
    storageBucket: 'app-5642b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHewRjH34GC2g4D4nh7Tcuf_0_odbCWjg',
    appId: '1:495262766796:android:303f31ee5549033c46d469',
    messagingSenderId: '495262766796',
    projectId: 'app-5642b',
    storageBucket: 'app-5642b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHewRjH34GC2g4D4nh7Tcuf_0_odbCWjg',
    appId: '1:495262766796:ios:your-ios-app-id',
    messagingSenderId: '495262766796',
    projectId: 'app-5642b',
    storageBucket: 'app-5642b.firebasestorage.app',
    iosBundleId: 'com.example.secure_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHewRjH34GC2g4D4nh7Tcuf_0_odbCWjg',
    appId: '1:495262766796:macos:your-macos-app-id',
    messagingSenderId: '495262766796',
    projectId: 'app-5642b',
    storageBucket: 'app-5642b.firebasestorage.app',
    iosBundleId: 'com.example.secure_app',
  );
}
